### ISSUE TITLE
import torch error

### ISSUE THREAD

**Issue by longmalongma** [hzxie/RMNet#1]
![image](https://user-images.githubusercontent.com/40291722/113959076-ca154b00-9854-11eb-8186-0979bd0dcfbb.png)
Thank you for your great work. I found your code stuck on the Import Torch line, but my environment was able to run other code. Do you know why?

**Comment by hzxie** [comment]
Please provide more error logs or stacktrace.

**Comment by hzxie** [comment]
I don't think the problem is related to our project.

**Comment by longmalongma** [comment]
> I don't think the problem is related to our project.

I can import torch when I use the command line to enter Python, but I'm stuck in the import torch line when I run codes. Why?My environment should be fine, because I can run other codes.
![image](https://user-images.githubusercontent.com/40291722/113972501-487de700-986d-11eb-8a27-ee5dafc787cc.png)

**Comment by hzxie** [comment]
Try to run the following commands in the Python interpreter:

```
import argparse
import importlib
import logging
import matplotlib
import numpy as np
import os
import random
import sys
import torch
```

**Comment by hzxie** [comment]
It seems that the code in the screenshot does not belong to our project.

**Comment by hzxie** [comment]
Therefore, all codes in your Python environment can not run normally.

**Comment by longmalongma** [comment]
> Therefore, all codes in your Python environment can not run normally.

Thanks for your help. I got it!
