### ISSUE TITLE
光流 .flo 文件

### ISSUE THREAD

**Issue by JoshonSmith** [hzxie/RMNet#12]
请问准备数据集的配置文件显示，需要数据集DAVIS的光流文件.flo。
这是需要我们自己去预先估计光流吗?

**Comment by hzxie** [comment]
As said in README:

Precompute the Optical Flow

- For the DAVIS dataset, the optical flows are computed by FlowNet2-CSS with the model pretrained on FlyingThings3D.
- For the YouTube-VOS dataset, the optical flows are computed by RAFT with the model pretrained on Sintel.
