### ISSUE TITLE
Hyperparameters for static image pretraining

### ISSUE THREAD

**Issue by Ali2500** [hzxie/RMNet#16]
I wanted to know what changes are necessary to train the first step on static images.
I commented out the following line from config.yaml:

`__C.DATASET.TRAIN_DATASET                        = ['YOUTUBE_VOS', 'DAVISx5']`

So that the image datasets are loaded. Is the number of epochs also different? I'm confirming because the image dataset has 27728 batches per epoch and training this for 200 epochs is extremely lengthy.

**Comment by hzxie** [comment]
Sorry I cannot remember it clearly.
Actually, you don't need to finish all batches for each epoch. Please stop it early.
