### ISSUE TITLE
Does Table 5 consider the computing time of optical flow?

### ISSUE THREAD

**Issue by bo-miao** [hzxie/RMNet#22]
Hi,

Thank you for your great work.

In table 5, the cross attention computing time is reduced significantly. May I know did you consider the computing time of optical flow in Table 5 since I noticed that tinyflownet also requires 10ms to compute, which is the same as the baseline cross attention computing time? 

Thank you.

**Comment by hzxie** [comment]
Sorry for the late reply.
Table 5 only reports the time of Regional Memory Reader, i.e., the time of TinyFlowNet is not included.
