### ISSUE TITLE
About training process

### ISSUE THREAD

**Issue by LingyiHongfd** [hzxie/RMNet#23]
Thanks for your job!
I have some problem about the training process.
1. The training of tiny_flownet. According to the implementation details section in paper, the tiny_flownet and the STM is co-trained during both pretraining on static images and fintuning on video datasets such as DAVIS. But according to the code and other issues, the tiny_flownet and STM is trained separately. And you didn't inform the order of the training of tiny_flownet and STM. I wonder how you train the model. Firstly train the tiny flownet on static images and the train STM on static images, then finetune the STM on video datasets. Or some other order?
2. For each training period, the hypeparameter and training epoch ?
I would appreciate it if you could reply.

**Comment by hzxie** [comment]
Sorry for the late reply.

For the first question, please refer to https://github.com/hzxie/RMNet/issues/3.
For the second question, I cannot remember the details clearly.
