### ISSUE TITLE
An example of YouTubeVOS used in the thesis

### ISSUE THREAD

**Issue by theRain0450** [hzxie/RMNet#29]
Hello and thank you very much for your work!
After swinging through your paper, I realized that the examples used in your paper are very typical, such as these two:
![image](https://github.com/user-attachments/assets/d7a8f1ee-550d-4caa-a28a-fe50f4accb94)
You mention in your paper that this is data from YouTubeVOS2018.
But it's not easy to find these examples in a huge dataset, if possible, can I know the id numbers of these examples so that I can look up the example data?
Looking forward to your reply, thank you for taking time out of your busy schedule to answer me.

**Comment by hzxie** [comment]
Sorry, I cannot find the ID of these examples. Because this work was done 4 years ago😂

**Comment by theRain0450** [comment]
> Sorry, I cannot find the ID of these examples. Because this work was done 4 years ago😂

Okay, thank you very much for your reply, I wish you a happy life and good luck~
