### ISSUE TITLE
About network training

### ISSUE THREAD

**Issue by suhwan-cho** [hzxie/RMNet#5]
Hi, thanks for your great work!

I understand that TinyFlowNet is trained with pre-computed optical flows of FlowNet (for DAVIS) and RAFT (for YouTube-VOS) that are trained from other datasets.
I want to know how TinyFlowNet and RMNet are trained during static image training stage, as there are no pre-computed results for those training samples.

**Comment by hzxie** [comment]
Following STM, we apply the affine transformation to synthesize videos from static images.
The affine transformation parameters are saved and used to generate the optical flow.

https://github.com/hzxie/RMNet/blob/8e3e1c7742191288f6c00ad7ab937aa12128fd6b/utils/data_transforms.py#L287-L302
