### ISSUE TITLE
reg_att_map_generator setup error

### ISSUE THREAD

**Issue by xjtuwh** [hzxie/RMNet#6]
reg_att_map_generator.cu(114): error: a pointer to a bound function may only be used to call the function
reg_att_map_generator.cu(114): error: type name is not allowed

reg_att_map_generator.cu(114): error: expected an expression

reg_att_map_generator.cu(114): error: a pointer to a bound function may only be used to call the function

reg_att_map_generator.cu(114): error: type name is not allowed

reg_att_map_generator.cu(114): error: expected an expression

reg_att_map_generator.cu(115): error: a pointer to a bound function may only be used to call the function

reg_att_map_generator.cu(115): error: type name is not allowed

reg_att_map_generator.cu(115): error: expected an expression

reg_att_map_generator.cu(115): error: a pointer to a bound function may only be used to call the function

reg_att_map_generator.cu(115): error: type name is not allowed

reg_att_map_generator.cu(115): error: expected an expression

12 errors detected in the compilation of "/tmp/tmpxft_000076b2_00000000-6_reg_att_map_generator.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by hzxie** [comment]
What's your PyTorch version, CUDA version, and GCC version?

**Comment by xjtuwh** [comment]
PyTorch：'1.1.0'
CUDA： 9.0
GCC：5.4.0 
Ubuntu： 16.04

**Comment by hzxie** [comment]
According to README, please use PyTorch >= 1.4.

> NOTE: PyTorch >= 1.4, CUDA >= 9.0 and GCC >= 4.9 are required.

**Comment by YinWeiling** [comment]
I have the same problem!
reg_att_map_generator.cu(114): error: a pointer to a bound function may only be used to call the function
reg_att_map_generator.cu(114): error: type name is not allowed
reg_att_map_generator.cu(114): error: expected an expression
reg_att_map_generator.cu(114): error: a pointer to a bound function may only be used to call the function
reg_att_map_generator.cu(114): error: type name is not allowed
reg_att_map_generator.cu(114): error: expected an expression
reg_att_map_generator.cu(115): error: a pointer to a bound function may only be used to call the function
reg_att_map_generator.cu(115): error: type name is not allowed
reg_att_map_generator.cu(115): error: expected an expression
reg_att_map_generator.cu(115): error: a pointer to a bound function may only be used to call the function
reg_att_map_generator.cu(115): error: type name is not allowed
reg_att_map_generator.cu(115): error: expected an expression
12 errors detected in the compilation of "/tmp/tmpxft_00007bfa_00000000-6_reg_att_map_generator.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

My torch=1.6.0, cuda=10.0,gcc=7.5.0. Could you please help me QAQ
